// export const CART_ADD_ITEM = 'CART_ADD_ITEM'
export const ADD_SHOPPING_ITEM = 'ADD_SHOPPING_ITEM';
export const DECREASE_SHOPPING_ITEM = "DECREASE_SHOPPING_ITEM"
export const SAVE_CALCULATION = 'SAVE_CALCULATION';
